# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa4f226072600a82f0b9988f0ecec3f6ec99687b246fb2fed019219de2c8a851799b9f25f347f50d15c05a2fb6fa3e4a376b4abd828384c3c3e718ffe6171035

test:
  secret_key_base: 5293ffbf54e09386534756281f3f3670e2d4f5e4151fe5d1e35bc7f57d01286966d4c49f8e21631c5a79e7b589ba3aee5397cc2c5ad67e7f79195a2541fa7ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
